default['hello_app']['db_user'] = 'hello_app'
default['hello_app']['db_name'] = 'hello_app'
default['hello_app']['server_name'] = 'hello_app.example.com'
default['hello_app']['docroot'] = '/srv/hello_app/current'
default['hello_app']['config_dir'] = '/srv/hello_app/shared/config'
